language: cpp

sudo: required
dist: xenial

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os: windows

compiler:
  - gcc

cache:
  directories:
    - ccache_llvm40
    - ccache_llvm50
    - ccache_llvm60

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./scripts/travis.sh osx initialize ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/travis.sh linux initialize ; fi

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./scripts/travis.sh osx build ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then ./scripts/travis.sh linux build ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./scripts/travis.bat ; fi

notifications:
  slack:
    secure: eW0eTnlEz1Pa68ZJOps7L0UscoxoFa+JLuOIOy4PPrLs1DfIiGdhHMfWs2U8mF8YaBYmrXgav/1IxNVtdPxiwfyLdYbiNSoEfo1ofPpizTH02flXthnUVIzlQD1jT6OSk840vskT2WWufBEkoaEIxFDXVI8PFtAtIYyfveVEnRdkTPUvuLV0pTX92c+ZCH3FIWtDey+4aVUwsttJSVloDSExy27LuoBLDPSNX8goiZFFrIcBRpspumysEJXdj5FSNiED9TQA1NCGWhsUqUlTPMYp1B8M/lKciugqhAlGijSL3lOisJZWsf/YZcto/N7wNMU54YNbfmMUZu6K9UkveVOD8qtlAs/8MDPyH0O+s/Hf2y6KGb7PSO9sxYF/WWRLNqxp8SgmY3IKu8niglXsHBNd4cXibvM3a2KJoJo453PI48XAfaygPYcYcuNedsQT9Fng384vpUjV7YLLU1452qTjx5T5SarjeF4ExtzJVYAQWhFT7RkNpdtDnKNLczwicM8wRSCHfEmGLR1Dpw5zQlS3uFJydTWTgAeLSHKKkfgqLYiR7/Ongv1M8Q+JUgYtF2dV9PLEpb0QGzw6B/RnW2vGNWIE+JJCjpZTizQj0f8UIh+k//v9jL4simVHRDPArnvJaFP0T4BrUl4Z4XN/dYFOogp9rCHgQCvqVOCPrFI=
